
pipeline {
	agent any
	
	stages {
		stage("Init") {
			steps {
				echo "============================="
				echo "This is feature/audio-driver branch"
				echo "============================="
			}
		}
	}
}

