
pipeline {
	agent any
	
	stages {
		stage("Build-master") {
            when {
                branch 'multi/master'
            }
			steps {
				echo "============================="
				echo "This is master branch"
				echo "============================="
			}
		}
		stage("Build-feature") {
            when {
                branch 'multi/feature/*'
            }
			steps {
				echo "============================="
				echo "This is feature branch"
				echo "============================="
				bat "exit 1"
			}
		}
	}
}

